/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CardPurchaseResponse {
    /// digits (1)
    #[serde(rename = "address_match", skip_serializing_if = "Option::is_none")]
    pub address_match: Option<i32>,
    /// characters (2)
    #[serde(rename = "card_type", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<String>,
    /// digits (2)
    #[serde(rename = "cvd_match", skip_serializing_if = "Option::is_none")]
    pub cvd_match: Option<i32>,
    /// digits (4)
    #[serde(rename = "last_four", skip_serializing_if = "Option::is_none")]
    pub last_four: Option<String>,
    /// digits (1)
    #[serde(rename = "postal_result", skip_serializing_if = "Option::is_none")]
    pub postal_result: Option<i32>,
}

impl CardPurchaseResponse {
    pub fn new() -> CardPurchaseResponse {
        CardPurchaseResponse {
            address_match: None,
            card_type: None,
            cvd_match: None,
            last_four: None,
            postal_result: None,
        }
    }
}


