/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CardGetTransactionResponse {
    /// digits (1)
    #[serde(rename = "address_match", skip_serializing_if = "Option::is_none")]
    pub address_match: Option<i32>,
    /// characters (1)
    #[serde(rename = "avs_result", skip_serializing_if = "Option::is_none")]
    pub avs_result: Option<String>,
    /// characters (2)
    #[serde(rename = "card_type", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<String>,
    /// digits (2)
    #[serde(rename = "cvd_match", skip_serializing_if = "Option::is_none")]
    pub cvd_match: Option<i32>,
    /// characters (2)
    #[serde(rename = "expiry_month", skip_serializing_if = "Option::is_none")]
    pub expiry_month: Option<String>,
    /// characters (2)
    #[serde(rename = "expiry_year", skip_serializing_if = "Option::is_none")]
    pub expiry_year: Option<String>,
    /// digits (4)
    #[serde(rename = "last_four", skip_serializing_if = "Option::is_none")]
    pub last_four: Option<String>,
}

impl CardGetTransactionResponse {
    pub fn new() -> CardGetTransactionResponse {
        CardGetTransactionResponse {
            address_match: None,
            avs_result: None,
            card_type: None,
            cvd_match: None,
            expiry_month: None,
            expiry_year: None,
            last_four: None,
        }
    }
}


