/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Custom {
    /// alphanumeric (256)
    #[serde(rename = "ref1", skip_serializing_if = "Option::is_none")]
    pub ref1: Option<String>,
    /// alphanumeric (256)
    #[serde(rename = "ref2", skip_serializing_if = "Option::is_none")]
    pub ref2: Option<String>,
    /// alphanumeric (256)
    #[serde(rename = "ref3", skip_serializing_if = "Option::is_none")]
    pub ref3: Option<String>,
    /// alphanumeric (256)
    #[serde(rename = "ref4", skip_serializing_if = "Option::is_none")]
    pub ref4: Option<String>,
    /// alphanumeric (256)
    #[serde(rename = "ref5", skip_serializing_if = "Option::is_none")]
    pub ref5: Option<String>,
}

impl Custom {
    pub fn new() -> Custom {
        Custom {
            ref1: None,
            ref2: None,
            ref3: None,
            ref4: None,
            ref5: None,
        }
    }
}


