/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Link {
    /// alphanumeric (256). Url to perform the void, return, completion etc.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// characters (16). Http method. post, put, get etc.
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// characters (16). Eg. \"void\" or \"return\"
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub _ref: Option<String>,
}

impl Link {
    pub fn new() -> Link {
        Link {
            href: None,
            method: None,
            _ref: None,
        }
    }
}


