/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModelReturn {
    /// The amount of the transaction to return. Must be less than or equal to the original purchase amount.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// alphanumeric (30)
    #[serde(rename = "order_number", skip_serializing_if = "Option::is_none")]
    pub order_number: Option<String>,
}

impl ModelReturn {
    pub fn new(amount: f64) -> ModelReturn {
        ModelReturn {
            amount,
            order_number: None,
        }
    }
}


