/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentRequest {
    /// A decimal value in dollars, or relevant currency. digits(9)
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "billing", skip_serializing_if = "Option::is_none")]
    pub billing: Option<Box<crate::models::Address>>,
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<crate::models::Card>>,
    /// alphanumeric (256)
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<Box<crate::models::Custom>>,
    /// alphanumeric (30)
    #[serde(rename = "customer_ip", skip_serializing_if = "Option::is_none")]
    pub customer_ip: Option<String>,
    /// characters (3)
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// A unique order number. alphanumeric(30)
    #[serde(rename = "order_number", skip_serializing_if = "Option::is_none")]
    pub order_number: Option<String>,
    /// One of (card, token, payment_profile, cash, cheque). characters(20)
    #[serde(rename = "payment_method")]
    pub payment_method: String,
    #[serde(rename = "payment_profile", skip_serializing_if = "Option::is_none")]
    pub payment_profile: Option<Box<crate::models::ProfilePurchase>>,
    #[serde(rename = "shipping", skip_serializing_if = "Option::is_none")]
    pub shipping: Option<Box<crate::models::Address>>,
    /// alphanumeric (256)
    #[serde(rename = "term_url", skip_serializing_if = "Option::is_none")]
    pub term_url: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<crate::models::TokenPurchase>>,
}

impl PaymentRequest {
    pub fn new(amount: f64, payment_method: String) -> PaymentRequest {
        PaymentRequest {
            amount,
            billing: None,
            card: None,
            comments: None,
            custom: None,
            customer_ip: None,
            language: None,
            order_number: None,
            payment_method,
            payment_profile: None,
            shipping: None,
            term_url: None,
            token: None,
        }
    }
}


