/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentProfile {
    #[serde(rename = "account_ref", skip_serializing_if = "Option::is_none")]
    pub account_ref: Option<String>,
    #[serde(rename = "billing", skip_serializing_if = "Option::is_none")]
    pub billing: Option<Box<crate::models::Address>>,
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<crate::models::GetProfileDefaultCard>>,
    /// digits(2)
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<Box<crate::models::Custom>>,
    /// alphanumeric(32)
    #[serde(rename = "customer_code", skip_serializing_if = "Option::is_none")]
    pub customer_code: Option<String>,
    /// characters(2)
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// date and time alphanumeric(24)
    #[serde(rename = "last_transaction", skip_serializing_if = "Option::is_none")]
    pub last_transaction: Option<String>,
    /// alphanumeric(64)
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// date and time it was last modified alphanumeric(24)
    #[serde(rename = "modified_date", skip_serializing_if = "Option::is_none")]
    pub modified_date: Option<String>,
    #[serde(rename = "profile_group", skip_serializing_if = "Option::is_none")]
    pub profile_group: Option<String>,
    /// characters(1)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "velocity_group", skip_serializing_if = "Option::is_none")]
    pub velocity_group: Option<String>,
}

impl PaymentProfile {
    pub fn new() -> PaymentProfile {
        PaymentProfile {
            account_ref: None,
            billing: None,
            card: None,
            code: None,
            custom: None,
            customer_code: None,
            language: None,
            last_transaction: None,
            message: None,
            modified_date: None,
            profile_group: None,
            status: None,
            velocity_group: None,
        }
    }
}


