/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileFromToken {
    /// The token received from the client-side tokenization service. alphanumeric(64)
    #[serde(rename = "code")]
    pub code: String,
    /// alphanumeric(64)
    #[serde(rename = "name")]
    pub name: String,
}

impl ProfileFromToken {
    pub fn new(code: String, name: String) -> ProfileFromToken {
        ProfileFromToken {
            code,
            name,
        }
    }
}


