/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileCard {
    /// digits(2)
    #[serde(rename = "expiry_month", skip_serializing_if = "Option::is_none")]
    pub expiry_month: Option<String>,
    /// digits(2)
    #[serde(rename = "expiry_year", skip_serializing_if = "Option::is_none")]
    pub expiry_year: Option<String>,
    /// cardholder name. alphanumeric(64)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Credit card number. digits(20)
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
}

impl ProfileCard {
    pub fn new() -> ProfileCard {
        ProfileCard {
            expiry_month: None,
            expiry_year: None,
            name: None,
            number: None,
        }
    }
}


