/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileGetCards {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Vec<crate::models::ProfileCards>>,
    /// digits(2)
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<f32>,
    /// characters(32)
    #[serde(rename = "customer_code", skip_serializing_if = "Option::is_none")]
    pub customer_code: Option<String>,
    /// alphanumeric(64)
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ProfileGetCards {
    pub fn new() -> ProfileGetCards {
        ProfileGetCards {
            card: None,
            code: None,
            customer_code: None,
            message: None,
        }
    }
}


