/*
 * Bambora Payments
 *
 * https://api.na.bambora.com
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokenRequest {
    /// a 3 to 4 digit representation of CVD/CDD. This is the number usually found on the back of the credit card.
    #[serde(rename = "cvd")]
    pub cvd: String,
    /// a 2 digit representation of the expiry month. For example March is 03.
    #[serde(rename = "expiry_month")]
    pub expiry_month: String,
    /// a 2 digit representation of the expiry year. For example 2016 is 16.
    #[serde(rename = "expiry_year")]
    pub expiry_year: String,
    /// The credit card number
    #[serde(rename = "number")]
    pub number: String,
}

impl TokenRequest {
    pub fn new(cvd: String, expiry_month: String, expiry_year: String, number: String) -> TokenRequest {
        TokenRequest {
            cvd,
            expiry_month,
            expiry_year,
            number,
        }
    }
}


